#!/usr/bin/env python3
"""
Generate migration 017 (seed content) from nidan/domain/content/cases.py.

    python scripts/generate_seed_migration.py

Generated rather than hand-written because it is 27 + 86 + 40 + 523 rows, and a
hand-typed transcription of 523 phrases would contain mistakes nobody would ever
find — a phrase that silently never matches looks exactly like a learner who
never asked.

Re-runnable: if the master lists in cases.py change, regenerate and the
migration follows. Until T-021 gives clinicians an editor, cases.py remains the
place content is authored, so this is the bridge rather than a one-off import.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from nidan.domain.assessment.topics import TOPIC_KEYWORDS  # noqa: E402
from nidan.domain.content.cases import (  # noqa: E402
    MASTER_EXAMINATIONS,
    MASTER_INVESTIGATIONS,
)

OUT = pathlib.Path(__file__).resolve().parent.parent / "migrations" / "versions" / "017_seed_content.py"


def _display_name(topic_key: str) -> str:
    """`meal_relationship` -> `Meal relationship`, matching the UI's own rule."""
    return topic_key.replace("_", " ").capitalize()


def build() -> str:
    exams = [
        {"key": k, "label": v["label"], "group_name": v["group"],
         "normal_result": v["normal_result"], "display_order": i}
        for i, (k, v) in enumerate(MASTER_EXAMINATIONS.items())
    ]
    investigations = [
        {"key": k, "label": v["label"], "group_name": v["group"],
         "normal_result": v["normal_result"], "display_order": i}
        for i, (k, v) in enumerate(MASTER_INVESTIGATIONS.items())
    ]
    topics = [
        {"topic_key": k, "display_name": _display_name(k), "phrases": list(v)}
        for k, v in TOPIC_KEYWORDS.items()
    ]
    n_phrases = sum(len(t["phrases"]) for t in topics)

    return f'''"""seed_content

Revision ID: 017
Revises: 016

Seeds the master lists (DATA_MODEL §9.2) — reference data the assessment engine
cannot work without: coverage scoring needs the topic lexicon, and the
examination and investigation menus are built from these tables.

GENERATED by scripts/generate_seed_migration.py from cases.py. Do not edit by
hand; regenerate. `display_order` is the order the items appear in cases.py, so
the menus keep the grouping learners already see.

  examinations    {len(exams)}
  investigations  {len(investigations)}
  topic_lexicon   {len(topics)}
  topic_phrases   {n_phrases}
"""

from __future__ import annotations

import json

from alembic import op

revision = "017"
down_revision = "016"
branch_labels = None
depends_on = None

EXAMINATIONS = json.loads(r"""{json.dumps(exams, ensure_ascii=False)}""")
INVESTIGATIONS = json.loads(r"""{json.dumps(investigations, ensure_ascii=False)}""")
TOPICS = json.loads(r"""{json.dumps(topics, ensure_ascii=False)}""")


def upgrade() -> None:
    bind = op.get_bind()

    for table, rows in (("examinations", EXAMINATIONS),
                        ("investigations", INVESTIGATIONS)):
        for r in rows:
            bind.exec_driver_sql(
                f"INSERT INTO {{table}} (key, label, group_name, normal_result, "
                "display_order) VALUES (%s, %s, %s, %s, %s)",
                (r["key"], r["label"], r["group_name"], r["normal_result"],
                 r["display_order"]),
            )

    # Phrases hang off their topic, so the id is needed before inserting them.
    for t in TOPICS:
        topic_id = bind.exec_driver_sql(
            "INSERT INTO topic_lexicon (topic_key, display_name) "
            "VALUES (%s, %s) RETURNING id",
            (t["topic_key"], t["display_name"]),
        ).scalar()
        for phrase in t["phrases"]:
            bind.exec_driver_sql(
                "INSERT INTO topic_phrases (topic_id, phrase) VALUES (%s, %s)",
                (topic_id, phrase),
            )


def downgrade() -> None:
    bind = op.get_bind()
    # topic_phrases goes first: it references topic_lexicon.
    bind.exec_driver_sql("DELETE FROM topic_phrases")
    bind.exec_driver_sql("DELETE FROM topic_lexicon")
    bind.exec_driver_sql("DELETE FROM investigations")
    bind.exec_driver_sql("DELETE FROM examinations")
'''


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(OUT.parent.parent.parent)} "
          f"— {len(MASTER_EXAMINATIONS)} exams, {len(MASTER_INVESTIGATIONS)} "
          f"investigations, {len(TOPIC_KEYWORDS)} topics, "
          f"{sum(len(v) for v in TOPIC_KEYWORDS.values())} phrases")
